import { useLocale } from 'next-intl';
import Header from '@/app/_components/common/Header/Header';
import Footer from '@/app/_components/common/Footer/Footer';
import type { Metadata } from "next";

export const metadata: Metadata = {
   title: "FinTech Fusion",
   description: "Generated by create next FinTechFusion offers an advanced automated trading platform designed to empower cryptocurrency traders by leveraging cutting-edge algorithms and real-time market analysis.",
};

type RootLayoutProps = {
   children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
   const locale = useLocale();
   return (
      <html lang={locale}  dir={locale === 'ar' ? 'rtl' : 'ltr'}>
         <body>
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
