import type { Metadata } from "next";
import Header from "../_components/common/Header/Header";
import Footer from "../_components/common/Footer/Footer";


export const metadata: Metadata = {
   title: "FinTech Fusion",
   description: "Generated by create next app",
};

type RootLayoutProps = {
   children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
   return (
      <html lang="en">
         <body>
            <Header />
            {children}
            <Footer />
         </body>
      </html>
   );
}
