import type { Metadata } from "next";
import Sidebar from "@/app/_components/common/dashboad/sidebar/SideBar";
import Headerdash from "@/app/_components/common/dashboad/Headerdash/Headerdash";
import { SidebarProvider } from '@/context/SidebarContext';

export const metadata: Metadata = {
   title: "FinTech Fusion",
   description: "Generated by create next app",
};


type DashboardLayoutProps = {
   children: React.ReactNode;
};

export default function UserDashboardLayout({ children }: DashboardLayoutProps) {
   return (
      <SidebarProvider>
         <div className="grid grid-cols-12">
            <div className="lg:col-span-2 col-span-10">
               <Sidebar />
            </div>
            <div className="lg:col-span-10 col-span-12 md:ps-5 ps-1 pe-1">
               <Headerdash />
               {children}
            </div>
         </div>
      </SidebarProvider>
   );
}
