import type { Metadata } from "next";
import { Roboto } from 'next/font/google'
import "../styles/globals.css";
import dynamic from 'next/dynamic';

const Header = dynamic(() => import('@/components/common/Header/Header'), { ssr: false });

const roboto = Roboto({ subsets: ["cyrillic"], weight: ["100", "300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: "FinTech Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
