// app/layout.tsx
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "../styles/globals.css";
import Header from "@/app/_components/common/Header/Header";
import Footer from "@/app/_components/common/Footer/Footer";
import { AuthProvider } from '@/context/AuthContext';
import 'react-toastify/dist/ReactToastify.css';

const roboto = Roboto({ subsets: ["cyrillic"], weight: ["100", "300", "400", "500", "700"] });

export const metadata: Metadata = {
  title: "FinTech Fusion",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <AuthProvider>
        <Header />
        {children}
        <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
