// app/layout.tsx
import type { Metadata } from "next";
import { Roboto } from 'next/font/google';
import "../styles/globals.css";
import { AuthProvider } from '@/context/AuthContext';
import AuthGuard from "@/context/AuthGuard";
import Header from "./_components/common/Header/Header";
import Footer from "./_components/common/Footer/Footer";

const roboto = Roboto({ subsets: ["cyrillic"], weight: ["100", "300", "400", "500", "700"] });

const metadata: Metadata = {
  title: "FinTech Fusion",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
  show?: boolean;

};

export default function RootLayout({
  children,
  show = true,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <AuthProvider>
          <AuthGuard>
            {show && <Header />}
            {children}
            <Footer/>
          </AuthGuard>
        </AuthProvider>
      </body>
    </html>
  );
}
