import { useLocale } from 'next-intl';
import type { Metadata } from "next";
import { SidebarProvider } from '@/context/SidebarContext';
import Sidebar from "@/app/_components/common/dashboard/sidebar/SideBar";
import Headerdash from "@/app/_components/common/dashboard/Headerdash/Headerdash";
import { AssetDataProvider } from "@/context/AssetsContext";
import WhatsAppIcon from "@/app/_components/common/contact/WhatsAppIcon";

export const metadata: Metadata = {
   title: "FinTech Fusion",
   description: "Generated by create next FinTechFusion offers an advanced automated trading platform designed to empower cryptocurrency traders by leveraging cutting-edge algorithms and real-time market analysis.",
};
type DashboardLayoutProps = {
   children: React.ReactNode;
};

export default function UserDashboardLayout({ children }: DashboardLayoutProps) {
   const locale = useLocale();
   return (
      <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
         <body>
            <SidebarProvider>
               <div className="grid grid-cols-12 gap-5">
                  <div className={`lg:col-span-3 col-span-10`}>
                     <Sidebar />
                  </div>
                  <div className={`lg:col-span-9 col-span-12`}>
                     <AssetDataProvider>
                        <Headerdash />
                     </AssetDataProvider>
                     <WhatsAppIcon />
                     {children}
                  </div>
               </div>
            </SidebarProvider>
         </body>
      </html>
   );
}
